# AIOT 敏感資訊 Secrets
# 注意：實際部署時應使用 kubectl create secret 或 sealed-secrets
apiVersion: v1
kind: Secret
metadata:
  name: aiot-database-secrets
  namespace: aiot
  labels:
    app.kubernetes.io/name: aiot-microservices
    app.kubernetes.io/component: database-secrets
type: Opaque
data:
  # MySQL 憑證 (base64 編碼)
  mysql-root-password: YWRtaW4=  # admin
  mysql-user: YWRtaW4=           # admin
  mysql-password: YWRtaW4=       # admin
  
  # MongoDB 憑證
  mongodb-username: YWRtaW4=     # admin
  mongodb-password: YWRtaW4=     # admin
  
  # RabbitMQ 憑證
  rabbitmq-username: YWRtaW4=    # admin
  rabbitmq-password: YWRtaW4=    # admin

---
apiVersion: v1
kind: Secret
metadata:
  name: aiot-app-secrets
  namespace: aiot
  labels:
    app.kubernetes.io/name: aiot-microservices
    app.kubernetes.io/component: application-secrets
type: Opaque
data:
  # JWT 密鑰
  jwt-secret: emFuZXduY2g=       # zanewnch
  
  # 其他應用程式密鑰可以在這裡添加
  # api-key: <base64-encoded-value>

---
# 監控服務密鑰
apiVersion: v1
kind: Secret
metadata:
  name: aiot-monitoring-secrets
  namespace: aiot
  labels:
    app.kubernetes.io/name: aiot-microservices
    app.kubernetes.io/component: monitoring-secrets
type: Opaque
data:
  # Grafana 管理員密碼
  grafana-admin-password: YWRtaW4=  # admin