# Kong Gateway 配置 ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: aiot-prod-kong-config
  namespace: aiot-prod
  labels:
    app: aiot-prod-kong
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: configuration
data:
  kong.yaml: |
    _format_version: "3.0"
    _transform: true
    
    # 服務定義
    services:
    - name: rbac-service
      url: http://rbac-service.aiot-prod.svc.cluster.local:3001
      tags:
      - rbac
      - microservice
      
    - name: drone-service-grpc
      url: grpc://aiot-prod-drone-service.aiot-prod.svc.cluster.local:50052
      tags:
      - drone
      - grpc
      
    - name: general-service-grpc
      url: grpc://aiot-prod-general-service.aiot-prod.svc.cluster.local:50053
      tags:
      - general
      - grpc
      
    - name: drone-websocket-service
      url: http://aiot-prod-drone-websocket-service.aiot-prod.svc.cluster.local:3004
      tags:
      - drone
      - websocket
    
    # 路由定義
    routes:
    - name: rbac-routes
      service: rbac-service
      paths:
      - /api/rbac
      strip_path: true
      
    - name: drone-grpc-routes
      service: drone-service-grpc
      paths:
      - /grpc/drone
      protocols:
      - grpc
      - grpcs
      
    - name: general-grpc-routes
      service: general-service-grpc
      paths:
      - /grpc/general
      protocols:
      - grpc
      - grpcs
      
    - name: drone-websocket-routes
      service: drone-websocket-service
      paths:
      - /ws/drone
      strip_path: true