apiVersion: v1
kind: Namespace
metadata:
  name: aiot
  labels:
    name: aiot
    app.kubernetes.io/name: aiot-microservices
    app.kubernetes.io/version: "1.0.0"
    environment: development
  annotations:
    description: "AIOT 微服務架構命名空間"
---
# 為 AIOT 命名空間設置預設網路政策（可選）
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aiot-default-deny
  namespace: aiot
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  egress:
  # 允許 DNS 查詢
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # 允許對外部服務的訪問
  - to: []
    ports:
    - protocol: TCP
  ingress:
  # 允許同命名空間內的通訊
  - from:
    - namespaceSelector:
        matchLabels:
          name: aiot