# AIOT 持久化存儲配置 - 單節點 Kubernetes 使用 hostPath
# 注意：hostPath 僅適用於單節點集群，生產環境建議使用 NFS 或雲端存儲

---
# MySQL 資料存儲
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: aiot
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/user/k8s-storage/aiot/mysql"
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: aiot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# MongoDB 資料存儲
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: aiot
  labels:
    type: local
    app: mongodb
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/user/k8s-storage/aiot/mongodb"
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: aiot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# Redis 資料存儲
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: aiot
  labels:
    type: local
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/user/k8s-storage/aiot/redis"
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: aiot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# RabbitMQ 資料存儲
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: aiot
  labels:
    type: local
    app: rabbitmq
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/user/k8s-storage/aiot/rabbitmq"
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: aiot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# Consul 資料存儲
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-pv
  namespace: aiot
  labels:
    type: local
    app: consul
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/user/k8s-storage/aiot/consul"
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
  namespace: aiot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

