openapi: 3.0.0
info:
  title: AIOT API
  version: 1.0.0
  description: API documentation for AIOT project
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /api/health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: string