# Frontend Dockerfile - React with TypeScript, Tailwind CSS, and SCSS
FROM node:18-alpine

WORKDIR /app

# Install dependencies
RUN npm install

# # Build the application
# RUN npm run build


# # Start the application
# CMD ["npm", "start"]
