_format_version: "3.0"

consumers:
  - username: aiot-jwt-consumer
    custom_id: aiot-system
    tags:
      - system
      - jwt

jwt_secrets:
  - consumer: aiot-jwt-consumer
    key: aiot-jwt-issuer
    secret: aiot-jwt-secret-key-2024
    algorithm: HS256
    tags:
      - jwt
      - system