_format_version: "3.0"

plugins:
  # JWT 插件 - RBAC 路由 (需要 JWT 驗證)
  - name: jwt
    route: rbac-routes
    config:
      secret_is_base64: false
      key_claim_name: iss
      claims_to_verify:
        - exp
        - iat
      header_names:
        - authorization
      cookie_names:
        - auth_token  # 從 auth_token cookie 提取 JWT
      uri_param_names: []
      anonymous: null
      run_on_preflight: true
    tags:
      - jwt
      - authentication
      - rbac

  # JWT 插件 - Drone API 路由 (需要 JWT 驗證)
  - name: jwt
    route: drone-api-routes
    config:
      secret_is_base64: false
      key_claim_name: iss
      claims_to_verify:
        - exp
        - iat
      header_names:
        - authorization
      cookie_names:
        - auth_token  # 從 auth_token cookie 提取 JWT
      uri_param_names: []
      anonymous: null
      run_on_preflight: true
    tags:
      - jwt
      - authentication
      - drone

  # JWT 插件 - Drone WebSocket 路由 (需要 JWT 驗證)
  - name: jwt
    route: drone-websocket-routes
    config:
      secret_is_base64: false
      key_claim_name: iss
      claims_to_verify:
        - exp
        - iat
      header_names:
        - authorization
      cookie_names:
        - auth_token  # 從 auth_token cookie 提取 JWT
      uri_param_names:
        - token  # WebSocket 也支援 URL 參數
      anonymous: null
      run_on_preflight: true
    tags:
      - jwt
      - authentication
      - websocket

  # JWT 插件 - General Service 路由 (需要 JWT 驗證)
  - name: jwt
    route: user-preferences-routes
    config:
      secret_is_base64: false
      key_claim_name: iss
      claims_to_verify:
        - exp
        - iat
      header_names:
        - authorization
      cookie_names:
        - auth_token  # 從 auth_token cookie 提取 JWT
      uri_param_names: []
      anonymous: null
      run_on_preflight: true
    tags:
      - jwt
      - authentication
      - general

  # JWT 插件 - Docs API 路由 (需要 JWT 驗證)
  - name: jwt
    route: docs-api-routes
    config:
      secret_is_base64: false
      key_claim_name: iss
      claims_to_verify:
        - exp
        - iat
      header_names:
        - authorization
      cookie_names:
        - auth_token  # 從 auth_token cookie 提取 JWT
      uri_param_names: []
      anonymous: null
      run_on_preflight: true
    tags:
      - jwt
      - authentication
      - docs

  # 注意：rbac-auth-routes (登入端點) 不需要 JWT 插件
  # 因為這是用戶取得 JWT Token 的地方

# Request Transformer 插件 - 將 JWT 信息傳遞給下游服務
request_transformer_plugins:
  # RBAC 服務 - 添加用戶信息到 headers
  - name: request-transformer
    route: rbac-routes
    config:
      add:
        headers:
          - "X-User-ID:$(authenticated_credential.username)"
          - "X-Username:$(authenticated_credential.username)"
          - "X-User-Roles:$(headers.x-authenticated-groups)"
          - "X-User-Permissions:$(headers.x-authenticated-scope)"
          - "X-User-Department:$(headers.x-user-department)"
          - "X-User-Level:$(headers.x-user-level)"
          - "X-Session-ID:$(headers.x-session-id)"
          - "X-Auth-Method:kong-jwt"
    tags:
      - jwt
      - headers
      - rbac

  # Drone 服務 - 添加用戶信息到 headers
  - name: request-transformer
    route: drone-api-routes
    config:
      add:
        headers:
          - "X-User-ID:$(authenticated_credential.username)"
          - "X-Username:$(authenticated_credential.username)"
          - "X-User-Roles:$(headers.x-authenticated-groups)"
          - "X-User-Permissions:$(headers.x-authenticated-scope)"
          - "X-User-Department:$(headers.x-user-department)"
          - "X-User-Level:$(headers.x-user-level)"
          - "X-Session-ID:$(headers.x-session-id)"
          - "X-Auth-Method:kong-jwt"
    tags:
      - jwt
      - headers
      - drone

  # General 服務 - 添加用戶信息到 headers
  - name: request-transformer
    route: user-preferences-routes
    config:
      add:
        headers:
          - "X-User-ID:$(authenticated_credential.username)"
          - "X-Username:$(authenticated_credential.username)"
          - "X-User-Roles:$(headers.x-authenticated-groups)"
          - "X-User-Permissions:$(headers.x-authenticated-scope)"
          - "X-User-Department:$(headers.x-user-department)"
          - "X-User-Level:$(headers.x-user-level)"
          - "X-Session-ID:$(headers.x-session-id)"
          - "X-Auth-Method:kong-jwt"
    tags:
      - jwt
      - headers
      - general

  # Docs 服務 - 添加用戶信息到 headers
  - name: request-transformer
    route: docs-api-routes
    config:
      add:
        headers:
          - "X-User-ID:$(authenticated_credential.username)"
          - "X-Username:$(authenticated_credential.username)"
          - "X-User-Roles:$(headers.x-authenticated-groups)"
          - "X-User-Permissions:$(headers.x-authenticated-scope)"
          - "X-User-Department:$(headers.x-user-department)"
          - "X-User-Level:$(headers.x-user-level)"
          - "X-Session-ID:$(headers.x-session-id)"
          - "X-Auth-Method:kong-jwt"
    tags:
      - jwt
      - headers
      - docs