_format_version: "3.0"
_transform: true

services:
  - name: rbac-service
    url: http://rbac-service:3001
    protocol: http
    host: rbac-service
    port: 3001
    path: /
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    routes:
      - name: rbac-routes
        paths:
          - /api/auth
          - /api/rbac
        strip_path: false
        preserve_host: false
        protocols:
          - http
          - https
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - Authorization
              exposed_headers:
                - X-Auth-Token
              credentials: true
              max_age: 3600
          - name: rate-limiting
            config:
              minute: 100
              hour: 1000
              policy: local
              hide_client_headers: false

  - name: drone-service
    url: http://drone-service:3002
    protocol: http
    host: drone-service
    port: 3002
    path: /
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    routes:
      - name: drone-routes
        paths:
          - /api/drone
        strip_path: false
        preserve_host: false
        protocols:
          - http
          - https
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - Authorization
              exposed_headers:
                - X-Auth-Token
              credentials: true
              max_age: 3600
          - name: rate-limiting
            config:
              minute: 200
              hour: 2000
              policy: local
              hide_client_headers: false
      - name: websocket-routes
        paths:
          - /socket.io
        strip_path: false
        preserve_host: false
        protocols:
          - http
          - https
          - ws
          - wss
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - Authorization
              credentials: true

  - name: fesetting-service
    url: http://fesetting-service:3003
    protocol: http
    host: fesetting-service
    port: 3003
    path: /
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    routes:
      - name: fesetting-routes
        paths:
          - /api/user-preferences
        strip_path: false
        preserve_host: false
        protocols:
          - http
          - https
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - Authorization
              credentials: true
              max_age: 3600
          - name: rate-limiting
            config:
              minute: 50
              hour: 500
              policy: local
              hide_client_headers: false

upstreams:
  - name: rbac-upstream
    algorithm: round-robin
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 10
          http_failures: 3
    targets:
      - target: rbac-service:3001
        weight: 100

  - name: drone-upstream
    algorithm: round-robin
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 10
          http_failures: 3
    targets:
      - target: drone-service:3002
        weight: 100

  - name: fesetting-upstream
    algorithm: round-robin
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 10
          http_failures: 3
    targets:
      - target: fesetting-service:3003
        weight: 100

plugins:
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true

  - name: request-id
    config:
      header_name: X-Request-ID
      echo_downstream: true

  - name: request-size-limiting
    config:
      allowed_payload_size: 10