_format_version: "3.0"

# ================================================================
# AIOT 完整 Kong DB-less 配置文件
# 包含 Services, Routes, Consumers, JWT 和 OPA 插件
# ================================================================

# ================================
# 消費者和 JWT 配置
# ================================
consumers:
  - username: aiot-jwt-consumer
    custom_id: aiot-system
    tags:
      - system
      - jwt

jwt_secrets:
  - consumer: aiot-jwt-consumer
    key: aiot-system  # 這個 key 對應 JWT payload 中的 iss 字段
    secret: aiot-jwt-secret-key-2024
    algorithm: HS256
    tags:
      - jwt
      - system

# ================================
# 微服務定義
# ================================
services:
  # RBAC 微服務 - 使用 HTTP 協議進行 Kong 通訊
  - name: rbac-service
    protocol: http
    host: aiot-rbac-service
    port: 3051
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - auth
      - rbac
      - microservice
      - http

  # Drone API 微服務 - 使用 HTTP 協議處理 API 請求
  - name: drone-http-service
    protocol: http
    host: aiot-drone-service
    port: 3052
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - drone
      - api
      - http

  # Drone WebSocket 微服務 - 專門處理 WebSocket 連線
  - name: drone-websocket-service
    protocol: ws
    host: aiot-drone-websocket-service
    port: 3004
    path: /socket.io
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - drone
      - websocket
      - realtime

  # General 微服務 - 使用 HTTP 協議 (原 FeSetting 服務)
  - name: general-service
    protocol: http
    host: aiot-general-service
    port: 3053
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - user-preferences
      - settings
      - general
      - http

  # Docs 微服務 - 使用 HTTP 協議處理文檔管理
  - name: docs-http-service
    protocol: http
    host: aiot-docs-service
    port: 3054
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - docs
      - documentation
      - api-docs
      - http

# ================================
# 路由配置
# ================================
routes:
  # RBAC 認證路由 - 支援 HTTP/HTTPS 訪問 (不需要認證)
  - name: rbac-auth-routes
    service: rbac-service
    paths:
      - /api/auth
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - auth
      - login
      - public

  # RBAC 管理路由 - 支援 HTTP/HTTPS 訪問 (需要認證)
  - name: rbac-routes
    service: rbac-service
    paths:
      - /api/rbac
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - rbac
      - permissions
      - secure

  # Drone API 路由 - 支援 HTTP/HTTPS 訪問 (需要認證)
  - name: drone-api-routes
    service: drone-http-service
    paths:
      - /api/drone
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - drone
      - api
      - secure
      - http

  # Drone WebSocket 路由 - 支援 WebSocket 連接 (需要認證)
  - name: drone-websocket-routes
    service: drone-websocket-service
    paths:
      - /socket.io
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
      - ws
      - wss
    tags:
      - drone
      - websocket
      - realtime
      - secure

  # User Preferences 路由 - 支援 HTTP/HTTPS 訪問 (需要認證)
  - name: user-preferences-routes
    service: general-service
    paths:
      - /api/user-preferences
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - user-preferences
      - settings
      - general
      - secure

  # Docs API 路由 - 支援 HTTP/HTTPS 訪問 (需要認證)
  - name: docs-api-routes
    service: docs-http-service
    paths:
      - /api/docs
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - docs
      - documentation
      - api-docs
      - secure
      - http

# ================================
# 插件配置
# ================================
plugins:
  # ===============================
  # JWT 認證插件 (按路由配置)
  # ===============================
  
  # JWT 插件 - RBAC 路由 (需要 JWT 驗證)
  - name: jwt
    route: rbac-routes
    config:
      secret_is_base64: false
      key_claim_name: iss
      claims_to_verify:
        - exp
        - iat
      header_names:
        - authorization
      cookie_names:
        - auth_token  # 從 auth_token cookie 提取 JWT
      uri_param_names: []
      anonymous: null
      run_on_preflight: true
    tags:
      - jwt
      - authentication
      - rbac

  # JWT 插件 - Drone API 路由 (需要 JWT 驗證)
  - name: jwt
    route: drone-api-routes
    config:
      secret_is_base64: false
      key_claim_name: iss
      claims_to_verify:
        - exp
        - iat
      header_names:
        - authorization
      cookie_names:
        - auth_token  # 從 auth_token cookie 提取 JWT
      uri_param_names: []
      anonymous: null
      run_on_preflight: true
    tags:
      - jwt
      - authentication
      - drone

  # JWT 插件 - Drone WebSocket 路由 (需要 JWT 驗證)
  - name: jwt
    route: drone-websocket-routes
    config:
      secret_is_base64: false
      key_claim_name: iss
      claims_to_verify:
        - exp
        - iat
      header_names:
        - authorization
      cookie_names:
        - auth_token  # 從 auth_token cookie 提取 JWT
      uri_param_names:
        - token  # WebSocket 也支援 URL 參數
      anonymous: null
      run_on_preflight: true
    tags:
      - jwt
      - authentication
      - websocket

  # JWT 插件 - General Service 路由 (需要 JWT 驗證)
  - name: jwt
    route: user-preferences-routes
    config:
      secret_is_base64: false
      key_claim_name: iss
      claims_to_verify:
        - exp
        - iat
      header_names:
        - authorization
      cookie_names:
        - auth_token  # 從 auth_token cookie 提取 JWT
      uri_param_names: []
      anonymous: null
      run_on_preflight: true
    tags:
      - jwt
      - authentication
      - general

  # JWT 插件 - Docs API 路由 (需要 JWT 驗證)
  - name: jwt
    route: docs-api-routes
    config:
      secret_is_base64: false
      key_claim_name: iss
      claims_to_verify:
        - exp
        - iat
      header_names:
        - authorization
      cookie_names:
        - auth_token  # 從 auth_token cookie 提取 JWT
      uri_param_names: []
      anonymous: null
      run_on_preflight: true
    tags:
      - jwt
      - authentication
      - docs

  # ===============================
  # Request Transformer 插件 - 將 JWT 信息傳遞給下游服務
  # ===============================
  
  # RBAC 服務 - 添加用戶信息到 headers
  - name: request-transformer
    route: rbac-routes
    config:
      add:
        headers:
          - "X-User-ID:$(headers.x-consumer-custom-id)"
          - "X-Username:$(headers.x-consumer-username)"
          - "X-Consumer-ID:$(headers.x-consumer-id)"
          - "X-Auth-Method:kong-jwt"
    tags:
      - jwt
      - headers
      - rbac

  # Drone 服務 - 添加用戶信息到 headers
  - name: request-transformer
    route: drone-api-routes
    config:
      add:
        headers:
          - "X-User-ID:$(headers.x-consumer-custom-id)"
          - "X-Username:$(headers.x-consumer-username)"
          - "X-Consumer-ID:$(headers.x-consumer-id)"
          - "X-Auth-Method:kong-jwt"
    tags:
      - jwt
      - headers
      - drone

  # General 服務 - 添加用戶信息到 headers
  - name: request-transformer
    route: user-preferences-routes
    config:
      add:
        headers:
          - "X-User-ID:$(headers.x-consumer-custom-id)"
          - "X-Username:$(headers.x-consumer-username)"
          - "X-Consumer-ID:$(headers.x-consumer-id)"
          - "X-Auth-Method:kong-jwt"
    tags:
      - jwt
      - headers
      - general

  # Docs 服務 - 添加用戶信息到 headers
  - name: request-transformer
    route: docs-api-routes
    config:
      add:
        headers:
          - "X-User-ID:$(headers.x-consumer-custom-id)"
          - "X-Username:$(headers.x-consumer-username)"
          - "X-Consumer-ID:$(headers.x-consumer-id)"
          - "X-Auth-Method:kong-jwt"
    tags:
      - jwt
      - headers
      - docs

  # ===============================
  # OPA 授權插件 (可選，如果需要細粒度權限控制)
  # ===============================
  
  # Kong 官方 OPA 插件 - RBAC 路由
  - name: opa
    route: rbac-routes
    config:
      opa_host: http://aiot-opa:8181
      opa_path: /v1/data/aiot/gateway/allow
      include_service_in_opa_input: true
      include_route_in_opa_input: true
      include_consumer_in_opa_input: true
    tags:
      - authorization
      - opa

  # Kong 官方 OPA 插件 - Drone 路由
  - name: opa
    route: drone-api-routes
    config:
      opa_host: http://aiot-opa:8181
      opa_path: /v1/data/aiot/gateway/allow
      include_service_in_opa_input: true
      include_route_in_opa_input: true
      include_consumer_in_opa_input: true
    tags:
      - authorization
      - opa

  # Kong 官方 OPA 插件 - General 路由
  - name: opa
    route: user-preferences-routes
    config:
      opa_host: http://aiot-opa:8181
      opa_path: /v1/data/aiot/gateway/allow
      include_service_in_opa_input: true
      include_route_in_opa_input: true
      include_consumer_in_opa_input: true
    tags:
      - authorization
      - opa

  # Kong 官方 OPA 插件 - Docs 路由
  - name: opa
    route: docs-api-routes
    config:
      opa_host: http://aiot-opa:8181
      opa_path: /v1/data/aiot/gateway/allow
      include_service_in_opa_input: true
      include_route_in_opa_input: true
      include_consumer_in_opa_input: true
    tags:
      - authorization
      - opa

  # ===============================
  # CORS 插件 - 跨來源請求支援
  # ===============================
  
  # CORS - Auth 路由
  - name: cors
    route: rbac-auth-routes
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

  # CORS - RBAC 路由
  - name: cors
    route: rbac-routes
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

  # CORS - Drone API 路由
  - name: cors
    route: drone-api-routes
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      credentials: true
      max_age: 3600

  # CORS - General 路由
  - name: cors
    route: user-preferences-routes
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      credentials: true
      max_age: 3600

  # CORS - Docs 路由
  - name: cors
    route: docs-api-routes
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      credentials: true
      max_age: 3600

  # ===============================
  # 性能優化插件
  # ===============================
  
  # Gzip 插件 - 回應壓縮（性能提升）
  - name: gzip
    config:
      types:
        - text/plain
        - text/html
        - text/css
        - text/xml
        - text/javascript
        - application/javascript
        - application/xml+rss
        - application/atom+xml
        - image/svg+xml
        - application/json
        - application/grpc
    tags:
      - performance
      - compression

  # Response Caching 插件 - API 回應快取（優化設定）
  - name: proxy-cache
    config:
      response_code:
        - 200
        - 301
        - 404
      request_method:
        - GET
        - HEAD
      content_type:
        - application/json
        - application/grpc
      cache_ttl: 60
      storage_ttl: 300
      strategy: memory
    tags:
      - performance
      - caching