_format_version: "3.0"

plugins:

  # Gzip 插件 - 回應壓縮（性能提升）
  - name: gzip
    config:
      types:
        - text/plain
        - text/html
        - text/css
        - text/xml
        - text/javascript
        - application/javascript
        - application/xml+rss
        - application/atom+xml
        - image/svg+xml
        - application/json
        - application/grpc
    tags:
      - performance
      - compression

  # Response Caching 插件 - API 回應快取（優化設定）
  - name: proxy-cache
    config:
      response_code:
        - 200
        - 301
        - 404
      request_method:
        - GET
        - HEAD
      content_type:
        - application/json
        - application/grpc
      cache_ttl: 60
      storage_ttl: 300
      strategy: memory
    tags:
      - performance
      - caching

  # Kong 官方 OPA 插件 - RBAC Auth 路由
  - name: opa
    route: rbac-auth-routes
    config:
      opa_host: http://aiot-opa:8181
      opa_path: /v1/data/aiot/gateway/allow
      include_service_in_opa_input: true
      include_route_in_opa_input: true
      include_consumer_in_opa_input: true
    tags:
      - authorization
      - opa

  # Kong 官方 OPA 插件 - RBAC 路由
  - name: opa
    route: rbac-routes
    config:
      opa_host: http://aiot-opa:8181
      opa_path: /v1/data/aiot/gateway/allow
      include_service_in_opa_input: true
      include_route_in_opa_input: true
      include_consumer_in_opa_input: true
    tags:
      - authorization
      - opa

  # Kong 官方 OPA 插件 - Drone 路由
  - name: opa
    route: drone-api-routes
    config:
      opa_host: http://aiot-opa:8181
      opa_path: /v1/data/aiot/gateway/allow
      include_service_in_opa_input: true
      include_route_in_opa_input: true
      include_consumer_in_opa_input: true
    tags:
      - authorization
      - opa

  # Kong 官方 OPA 插件 - General 路由 (原 FE Setting 服務)
  - name: opa
    route: general-routes
    config:
      opa_host: http://aiot-opa:8181
      opa_path: /v1/data/aiot/gateway/allow
      include_service_in_opa_input: true
      include_route_in_opa_input: true
      include_consumer_in_opa_input: true
    tags:
      - authorization
      - opa

  # Kong 官方 OPA 插件 - Docs 路由
  - name: opa
    route: docs-api-routes
    config:
      opa_host: http://aiot-opa:8181
      opa_path: /v1/data/aiot/gateway/allow
      include_service_in_opa_input: true
      include_route_in_opa_input: true
      include_consumer_in_opa_input: true
    tags:
      - authorization
      - opa

  # CORS 插件 - 應用到所有路由
  - name: cors
    route: rbac-auth-routes
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

  - name: cors
    route: rbac-routes
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

  - name: cors
    route: drone-api-routes
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      credentials: true
      max_age: 3600

  - name: cors
    route: general-routes
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      credentials: true
      max_age: 3600

  - name: cors
    route: docs-api-routes
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      credentials: true
      max_age: 3600
