_format_version: "3.0"

routes:
  # RBAC 認證路由 - 支援 HTTP/HTTPS 訪問
  - name: rbac-auth-routes
    service: rbac-service
    paths:
      - /api/auth
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - auth
      - login
      - secure

  # RBAC 管理路由 - 支援 HTTP/HTTPS 訪問
  - name: rbac-routes
    service: rbac-service
    paths:
      - /api/rbac
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - rbac
      - permissions
      - secure

  # Drone API 路由 - 支援 HTTP/HTTPS 訪問
  - name: drone-api-routes
    service: drone-http-service
    paths:
      - /api/drone
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - drone
      - api
      - secure
      - http

  # Drone WebSocket 路由 - 支援 WebSocket 連接
  - name: drone-websocket-routes
    service: drone-websocket-service
    paths:
      - /socket.io
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
      - ws
      - wss
    tags:
      - drone
      - websocket
      - realtime
      - secure

  # User Preferences 路由 - 支援 HTTP/HTTPS 訪問
  - name: user-preferences-routes
    service: general-service
    paths:
      - /api/user-preferences
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - user-preferences
      - settings
      - general
      - secure

  # Health Check 路由 - 支援 HTTP/HTTPS 訪問
  - name: health-routes
    service: general-service
    paths:
      - /api/health
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - health
      - monitoring
      - general
      - secure

  # Service Info 路由 - 支援 HTTP/HTTPS 訪問
  - name: info-routes
    service: general-service
    paths:
      - /api/info
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - info
      - general
      - secure

  # Docs API 路由 - 支援 HTTP/HTTPS 訪問
  - name: docs-api-routes
    service: docs-http-service
    paths:
      - /api/docs
    strip_path: true
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - docs
      - documentation
      - api-docs
      - secure
      - http