_format_version: "3.0"

services:
  # RBAC 微服務 - 使用 HTTP 協議進行 Kong 通訊
  - name: rbac-service
    protocol: http
    host: aiot-rbac-service
    port: 3051
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - auth
      - rbac
      - microservice
      - http

  # Drone API 微服務 - 使用 HTTP 協議處理 API 請求
  - name: drone-http-service
    protocol: http
    host: aiot-drone-service
    port: 3052
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - drone
      - api
      - http

  # Drone WebSocket 微服務 - 專門處理 WebSocket 連線
  - name: drone-websocket-service
    protocol: ws
    host: aiot-drone-websocket-service
    port: 3004
    path: /socket.io
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - drone
      - websocket
      - realtime

  # General 微服務 - 使用 HTTP 協議 (原 FeSetting 服務)
  - name: general-service
    protocol: http
    host: aiot-general-service
    port: 3053
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - user-preferences
      - settings
      - general
      - http

  # Docs 微服務 - 使用 HTTP 協議處理文檔管理
  - name: docs-http-service
    protocol: http
    host: aiot-docs-service
    port: 3054
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - docs
      - documentation
      - api-docs
      - http