_format_version: "3.0"

services:
  # RBAC 微服務 - 使用 gRPC 協議進行內部通訊
  - name: rbac-service
    protocol: grpc
    host: rbac-service.service.consul
    port: 50051
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - auth
      - rbac
      - microservice
      - grpc

  # Drone API 微服務 - 使用 gRPC 協議處理 API 請求
  - name: drone-grpc-service
    protocol: grpc
    host: drone-service.service.consul
    port: 50052
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - drone
      - api
      - grpc

  # Drone WebSocket 微服務 - 專門處理 WebSocket 連線
  - name: drone-websocket-service
    protocol: ws
    host: drone-websocket-service.service.consul
    port: 3004
    path: /socket.io
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - drone
      - websocket
      - realtime

  # General 微服務 - 使用 gRPC 協議
  - name: general-service
    protocol: grpc
    host: general-service.service.consul
    port: 50053
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - general
      - documentation
      - grpc

  # 文檔服務 - 統一管理所有微服務的 TypeDoc 文檔
  - name: docs-service
    protocol: http
    host: docs-service.service.consul
    port: 3005
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - documentation
      - typedoc
      - static
      - http