_format_version: "3.0"

services:
  # RBAC 微服務 - 使用 gRPC 協議進行內部通訊
  - name: rbac-service
    protocol: grpc
    host: aiot-rbac-service
    port: 50051
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - auth
      - rbac
      - microservice
      - grpc

  # Drone API 微服務 - 使用 gRPC 協議處理 API 請求
  - name: drone-grpc-service
    protocol: grpc
    host: aiot-drone-service
    port: 50052
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - drone
      - api
      - grpc

  # Drone WebSocket 微服務 - 專門處理 WebSocket 連線
  - name: drone-websocket-service
    protocol: ws
    host: aiot-drone-websocket-service
    port: 3004
    path: /socket.io
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - drone
      - websocket
      - realtime

  # General 微服務 - 使用 gRPC 協議 (原 FeSetting 服務)
  - name: general-service
    protocol: grpc
    host: aiot-general-service
    port: 50053
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - user-preferences
      - settings
      - general
      - grpc

  # Docs 微服務 - 使用 gRPC 協議處理文檔管理
  - name: docs-grpc-service
    protocol: grpc
    host: aiot-docs-service
    port: 50054
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 15000
    retries: 5
    tags:
      - docs
      - documentation
      - api-docs
      - grpc