_format_version: "3.0"

services:
  # RBAC 微服務 - 使用 gRPC 協議進行內部通訊
  - name: rbac-service
    protocol: grpc
    host: aiot-rbac-service
    port: 50051
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - auth
      - rbac
      - microservice
      - grpc

  # Drone API 微服務 - 使用 gRPC 協議處理 API 請求
  - name: drone-grpc-service
    protocol: grpc
    host: aiot-drone-service
    port: 50052
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - drone
      - api
      - grpc

  # Drone 即時通訊微服務 - 專門處理 WebSocket 連線
  - name: drone-realtime-service
    protocol: ws
    host: aiot-drone-realtime-service
    port: 3004
    path: /socket.io
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - drone
      - websocket
      - realtime

  # FeSetting 微服務 - 使用 gRPC 協議
  - name: fesetting-service
    protocol: grpc
    host: aiot-fesetting-service
    port: 50053
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - user-preferences
      - settings
      - grpc