_format_version: "3.0"

services:
  - name: rbac-service
    url: http://rbac-service:3001
    protocol: http
    host: rbac-service
    port: 3001
    path: /
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - auth
      - rbac
      - microservice

  - name: drone-service
    url: http://drone-service:3002
    protocol: http
    host: drone-service
    port: 3002
    path: /
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - drone
      - iot
      - websocket

  - name: fesetting-service
    url: http://fesetting-service:3003
    protocol: http
    host: fesetting-service
    port: 3003
    path: /
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    tags:
      - user-preferences
      - settings