# Docs 文檔服務 Kubernetes 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-service-deployment
  namespace: aiot
  labels:
    app: docs-service
    app.kubernetes.io/name: docs-service
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: aiot-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs-service
  template:
    metadata:
      labels:
        app: docs-service
    spec:
      containers:
      - name: docs-service
        image: node:18-bullseye  # 使用基礎鏡像
        ports:
        - containerPort: 3005
          name: http
        env:
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: aiot-microservice-config
              key: DOCS_SERVICE_NAME
        - name: SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: aiot-microservice-config
              key: DOCS_SERVICE_PORT
        # 從公共配置引入環境變數
        envFrom:
        - configMapRef:
            name: aiot-common-config
        - configMapRef:
            name: dev-environment-config
        # 開發模式：使用 ConfigMap 和 emptyDir
        volumeMounts:
        - name: app-workspace
          mountPath: /app
        - name: source-files
          mountPath: /app/package.json
          subPath: package.json
        - name: source-files
          mountPath: /app/nodemon.json
          subPath: nodemon.json
        - name: source-files
          mountPath: /app/tsconfig.json
          subPath: tsconfig.json
        - name: route-configs
          mountPath: /app/configs
          readOnly: true
        # 開發模式啟動命令
        command: ['sh', '-c', 'mkdir -p src && echo "console.log(\"Docs Service starting in development mode\"); process.exit(0);" > src/server.ts && npm install && npm run dev']
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
      volumes:
      - name: app-workspace
        emptyDir: {}
      - name: source-files
        configMap:
          name: docs-service-template
      - name: route-configs
        configMap:
          name: route-configs
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: docs-service
  namespace: aiot
  labels:
    app: docs-service
    app.kubernetes.io/name: docs-service
    app.kubernetes.io/component: microservice
spec:
  selector:
    app: docs-service
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
    name: http
  type: ClusterIP