# Drone 微服務 Kubernetes 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiot-prod-drone-service-deployment
  namespace: aiot-prod
  labels:
    app: aiot-prod-drone-service
    app.kubernetes.io/name: aiot-prod-drone-service
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: aiot-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiot-prod-drone-service
  template:
    metadata:
      labels:
        app: aiot-prod-drone-service
    spec:
      containers:
      - name: aiot-prod-drone-service
        image: aiot-drone-service:latest
        # 測試用啟動命令 - 保持容器運行
        command: ['npm', 'run', 'dev']
        ports:
        - containerPort: 50052
          name: grpc
        env:
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: aiot-microservice-config
              key: DRONE_SERVICE_NAME
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: aiot-microservice-config
              key: DRONE_GRPC_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: aiot-microservice-config
              key: DRONE_DB_NAME
        # 從公共配置引入環境變數
        envFrom:
        - configMapRef:
            name: aiot-common-config
        - configMapRef:
            name: prod-environment-config
        - secretRef:
            name: aiot-database-secrets
        - secretRef:
            name: aiot-app-secrets
        # 生產環境：僅掛載日誌儲存
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        livenessProbe:
          tcpSocket:
            port: 50052
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 50052
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
      volumes:
      - name: app-logs
        emptyDir: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: aiot-prod-drone-service
  namespace: aiot-prod
  labels:
    app: aiot-prod-drone-service
    app.kubernetes.io/name: aiot-prod-drone-service
    app.kubernetes.io/component: microservice
spec:
  selector:
    app: aiot-prod-drone-service
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
    name: grpc
  type: ClusterIP