# RBAC 微服務 - 生產環境 Kubernetes 配置
# ☸️ Production Only - 高可用、自動擴展、資源控制

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-service-deployment
  namespace: aiot-prod
  labels:
    app: rbac-service
    app.kubernetes.io/name: rbac-service
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: aiot-microservices
    app.kubernetes.io/version: "1.0.0"
    tier: backend
    environment: production
spec:
  replicas: 3  # 生產環境多副本
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: rbac-service
      environment: production
  template:
    metadata:
      labels:
        app: rbac-service
        environment: production
        tier: backend
    spec:
      # 生產級安全配置
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      
      # 節點選擇 (可選)
      nodeSelector:
        node-role: worker
      
      containers:
      - name: rbac-service
        # 生產環境使用預構建映像檔
        image: aiot/rbac-service:latest
        imagePullPolicy: Always
        
        ports:
        - containerPort: 3001
          name: http
        - containerPort: 50051
          name: grpc
        
        # 生產環境變數
        envFrom:
        - configMapRef:
            name: aiot-common-config
        - configMapRef:
            name: prod-environment-config
        - secretRef:
            name: aiot-secrets
            
        env:
        - name: SERVICE_NAME
          value: "rbac-service"
        - name: HTTP_PORT
          value: "3001"
        - name: GRPC_PORT
          value: "50051"
        - name: SERVICE_VERSION
          value: "1.0.0"
        
        # 資源限制 (生產環境)
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # 健康檢查
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # 啟動探針
        startupProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10

---
# RBAC Service - Production Service
apiVersion: v1
kind: Service
metadata:
  name: rbac-service
  namespace: aiot-prod
  labels:
    app: rbac-service
    app.kubernetes.io/name: rbac-service
    app.kubernetes.io/component: microservice
    environment: production
spec:
  type: ClusterIP
  selector:
    app: rbac-service
    environment: production
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP

---
# RBAC Service - HPA (生產環境自動擴展)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rbac-service-hpa
  namespace: aiot-prod
  labels:
    app: rbac-service
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rbac-service-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30

---
# RBAC Service - Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rbac-service-pdb
  namespace: aiot-prod
  labels:
    app: rbac-service
    environment: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: rbac-service
      environment: production