# Kong API Gateway Kubernetes 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-deployment
  namespace: aiot
  labels:
    app: kong
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: aiot-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:3.4
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8443
          name: proxy-ssl
        - containerPort: 8001
          name: admin
        - containerPort: 8444
          name: admin-ssl
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/kong/kong-main.yaml"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        - name: KONG_PLUGINS
          value: "bundled"
        # 移除自定義 DNS 解析器，使用 Kubernetes 默認
        volumeMounts:
        - name: kong-config
          mountPath: /kong
          readOnly: true
        livenessProbe:
          exec:
            command:
            - kong
            - health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
      volumes:
      - name: kong-config
        configMap:
          name: route-configs
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: kong-service
  namespace: aiot
  labels:
    app: kong
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: api-gateway
spec:
  selector:
    app: kong
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: proxy
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: proxy-ssl
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: admin
  - port: 8444
    targetPort: 8444
    protocol: TCP
    name: admin-ssl
  type: ClusterIP

---
# Kong 對外暴露服務 (LoadBalancer 或 NodePort)
apiVersion: v1
kind: Service
metadata:
  name: kong-external-service
  namespace: aiot
  labels:
    app: kong
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: api-gateway-external
spec:
  selector:
    app: kong
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: proxy
    nodePort: 30000
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: admin
    nodePort: 30001
  type: NodePort