# MySQL 資料庫服務 Kubernetes 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: aiot
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: aiot-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aiot-database-secrets
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: aiot-database-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aiot-database-secrets
              key: mysql-password
        - name: MYSQL_DATABASE
          value: "main_db"
        - name: TZ
          value: "Asia/Taipei"
        - name: MYSQL_INITDB_SKIP_TZINFO
          value: "1"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-init-scripts
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - admin
            - -padmin
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - admin
            - -padmin
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-init-scripts
        configMap:
          name: mysql-init-scripts
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: aiot
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  type: ClusterIP