version: '3.8'

services:
  opa-server:
    image: openpolicyagent/opa:latest-envoy
    container_name: AIOT-opa-server
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--config-file=/etc/opa/config.yaml"
      - "/etc/opa/policies"
    volumes:
      - ./server/config.yaml:/etc/opa/config.yaml:ro
      - ./policies:/etc/opa/policies:ro
      - ./data:/etc/opa/data:ro
    networks:
      - aiot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - OPA_LOG_LEVEL=info
      - OPA_LOG_FORMAT=json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opa.rule=Host(`opa.localhost`)"
      - "traefik.http.services.opa.loadbalancer.server.port=8181"

  opa-bundle-server:
    image: nginx:alpine
    container_name: AIOT-opa-bundle-server
    ports:
      - "8080:80"
    volumes:
      - ./bundles:/usr/share/nginx/html:ro
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - aiot-network
    restart: unless-stopped
    depends_on:
      - opa-server

networks:
  aiot-network:
    external: true